
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goojakgyo?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    database: mysql
    #    InnoDB
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      # ?? update or validate? ??
      ddl-auto: update
    show_sql: true

jwt:
  # goojakgyoaccesstokengoojakgyoaccesstokengoojakgyoaccesstokengoojakgyoaccesstoken
  secretKey: Z29vamFrZ3lvYWNjZXNzdG9rZW5nb29qYWtneW9hY2Nlc3N0b2tlbmdvb2pha2d5b2FjY2Vzc3Rva2VuZ29vamFrZ3lvYWNjZXNzdG9rZW4=
  access-expiration: 30 # 30분
  refresh-expiration: 4320 # 3일

oauth:
  google:
    clientIdPlaceholder: xxxx
    clientSecretPlaceholder: yyyy
    redirect-uri: http://localhost:3000/oauth/google/redirect
  kakao:
    clientIdPlaceholder: xxxx
    redirect-uri: http://localhost:3000/oauth/kakao/redirect
  naver:
    clientIdPlaceholder: xxxx
    clientSecretPlaceholder: yyyy
    redirect-uri: http://localhost:3000/oauth/naver/redirect

  # 디버깅을 위해 로그 레벨 수준 제어 코드 추가
  logging:
    level:
      root: INFO
      org.springframework: DEBUG
      org.springframework.web: DEBUG